"""add correlation rules tables

Revision ID: 07057fb3790e
Revises: 6b1eb55100a0
Create Date: 2026-01-25 11:00:17.539251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07057fb3790e'
down_revision: Union[str, None] = '6b1eb55100a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attack_techniques', 'is_subtechnique',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('attack_techniques', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_attack_techniques_parent_id', table_name='attack_techniques')
    op.drop_index('ix_attack_techniques_tactic_id', table_name='attack_techniques')
    op.alter_column('rule_attack_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_rule_attack_mappings_rule_id', table_name='rule_exceptions')
    op.drop_index('ix_rule_attack_mappings_technique_id', table_name='rule_attack_mappings')
    op.drop_index('ix_rule_exceptions_rule_id', table_name='rule_exceptions')

    # Create correlation_rules table
    op.create_table(
        'correlation_rules',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('rule_a_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('rule_b_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('entity_field', sa.String(length=100), nullable=False),
        sa.Column('time_window_minutes', sa.Integer(), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=True, server_default='true'),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['rule_a_id'], ['rules.id'], ),
        sa.ForeignKeyConstraint(['rule_b_id'], ['rules.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create correlation_state table
    op.create_table(
        'correlation_state',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('correlation_rule_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('entity_value', sa.String(length=500), nullable=False),
        sa.Column('rule_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('alert_id', sa.String(length=100), nullable=False),
        sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['correlation_rule_id'], ['correlation_rules.id'], ),
        sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_correlation_lookup', 'correlation_state', ['correlation_rule_id', 'entity_value', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_correlation_lookup', table_name='correlation_state')
    op.drop_table('correlation_state')
    op.drop_table('correlation_rules')
    op.create_index('ix_rule_exceptions_rule_id', 'rule_exceptions', ['rule_id'], unique=False)
    op.create_index('ix_rule_attack_mappings_technique_id', 'rule_attack_mappings', ['technique_id'], unique=False)
    op.create_index('ix_rule_attack_mappings_rule_id', 'rule_attack_mappings', ['rule_id'], unique=False)
    op.alter_column('rule_attack_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_attack_techniques_tactic_id', 'attack_techniques', ['tactic_id'], unique=False)
    op.create_index('ix_attack_techniques_parent_id', 'attack_techniques', ['parent_id'], unique=False)
    op.alter_column('attack_techniques', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attack_techniques', 'is_subtechnique',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
