"""add_field_mappings

Revision ID: 4d4c9cbc520f
Revises: 1cb102ecf21a
Create Date: 2026-01-23 15:19:40.501183

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d4c9cbc520f'
down_revision: str | None = '1cb102ecf21a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index_pattern_id', sa.UUID(), nullable=True),
    sa.Column('sigma_field', sa.String(length=255), nullable=False),
    sa.Column('target_field', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.Enum('MANUAL', 'AI_SUGGESTED', name='mappingorigin'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['index_pattern_id'], ['index_patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_pattern_id', 'sigma_field', name='uq_mapping_scope_field')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_mappings')
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS mappingorigin")
    # ### end Alembic commands ###
